// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";

export component Horizontal inherits HorizontalLayout {
    padding: MaterialStyleMetrics.padding_4;
    spacing: MaterialStyleMetrics.spacing_4;
}
