// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { MaterialPalette } from "../styling/material_palette.slint";

export global MaterialWindowAdapter {
    in property <bool> disable_hover;
}

export component MaterialWindow inherits Window {
    in property <bool> disable_hover;

    background: MaterialPalette.background;

    changed disable_hover => {
        MaterialWindowAdapter.disable_hover = root.disable_hover;
    }
}
