// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialTypography,
    TextStyle,
} from "../styling/material_typography.slint";
import { MaterialPalette } from "../styling/material_palette.slint";

export component MaterialText inherits Text {
    in property <TextStyle> style: MaterialTypography.label_large_prominent;

    font_size: root.style.font_size;
    font_weight: root.style.font_weight;
    letter-spacing: root.style.letter_spacing;
    color: MaterialPalette.on_background;
    overflow: elide;
}
