// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { MaterialText } from "./material_text.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialTypography } from "../styling/material_typography.slint";

export component ToolTip {
    in property <string> text;
    in property <length> hovered_x;
    in property <length> hovered_y;
    in property <length> hovered_width;
    in property <length> hovered_height;
    in property <length> parent_width;
    in property <length> parent_height;

    property <length> pref_w: background_layer.preferred_width;
    property <length> pref_h: background_layer.preferred_height;

    property <length> offset_x: 12px;
    property <length> offset_y: 16px;

    x: (root.hovered_x + root.offset_x + root.pref_w > root.parent_width - 8px) ? max(8px, root.hovered_x - root.pref_w - root.offset_x) : (root.hovered_x + root.offset_x);
    y: (root.hovered_y + root.offset_y + root.pref_h > root.parent_height - 8px) ? max(8px, root.hovered_y - root.pref_h - 8px) : (root.hovered_y + root.offset_y);

    z: 10000;

    opacity: root.visible ? 1.0 : 0.0;
    animate opacity { duration: 100ms; easing: ease-in; }

    background_layer := Rectangle {
        border_radius: 4px;
        background: MaterialPalette.inverse_surface;

        layout := VerticalLayout {
            padding_top: 4px;
            padding_bottom: 4px;
            padding_left: 8px;
            padding_right: 8px;

            MaterialText {
                text: root.text;
                max-width: 190px;
                vertical_alignment: center;
                horizontal_alignment: center;
                color: MaterialPalette.inverse_on_surface;
                style: MaterialTypography.body_medium;
                wrap: word-wrap;
                overflow: clip;
            }
        }
    }
}
