// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { MaterialText } from "./material_text.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialTypography } from "../styling/material_typography.slint";

export component ToolTip {
    in property <string> text;
    in property <length> hovered_x;
    in property <length> hovered_y;
    in property <length> hovered_width;
    in property <length> hovered_height;
    in property <length> parent_width;
    in property <length> parent_height;

    x: max(8px, min(root.parent_width - self.width - 8px, root.hovered_x + (root.hovered_width - self.width) / 2));
    y: (root.hovered_y + root.hovered_height + self.height + 6px > root.parent_height) ? (root.hovered_y - self.height - 6px) : (root.hovered_y + root.hovered_height + 6px);

    z: 10000;

    opacity: root.visible ? 1.0 : 0.0;
    animate opacity { duration: 100ms; easing: ease-in; }

    background_layer := Rectangle {
        border_radius: 4px;
        background: MaterialPalette.inverse_surface;

        layout := VerticalLayout {
            padding_top: 4px;
            padding_bottom: 4px;
            padding_left: 8px;
            padding_right: 8px;

            MaterialText {
                text: root.text;
                max-width: 190px;
                vertical_alignment: center;
                horizontal_alignment: center;
                color: MaterialPalette.inverse_on_surface;
                style: MaterialTypography.body_medium;
                wrap: word-wrap;
                overflow: clip;
            }
        }
    }
}
