import {
    MaterialStyleMetrics,
    MaterialTypography,
    FilledCard,
    ExpandableHeader,
    TextField,
    ScrollView,
    MaterialText,
} from "@material";
import { BondCutoff } from "../Types.slint";

export component BondCutoffsCard inherits FilledCard {
    in-out property <bool> expanded: false;
    in property <bool> file_loaded;
    in-out property <[BondCutoff]> bond_cutoffs;

    property <length> bond_cutoffs_height: root.expanded ? min(150px, root.bond_cutoffs.length * 50px) : 0px;

    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_4;
        spacing: MaterialStyleMetrics.spacing_4;

        ExpandableHeader {
            text: "Bond Cutoffs";
            expanded <=> root.expanded;
        }

        VerticalLayout {
            height: root.bond_cutoffs_height;
            visible: self.height > 0.1px;
            opacity: root.expanded ? 1.0 : 0.0;
            animate height {
                duration: 250ms;
                easing: ease-in-out;
            }
            animate opacity {
                duration: 250ms;
                easing: ease-in-out;
            }
            spacing: MaterialStyleMetrics.spacing_8;
            padding_left: MaterialStyleMetrics.spacing_8;

            ScrollView {
                vertical-stretch: 0;
                height: min(list_layout.preferred-height, root.bond_cutoffs_height);
                viewport-height: list_layout.preferred-height;
                viewport-width: list_layout.preferred-width;
                list_layout := VerticalLayout {
                    spacing: MaterialStyleMetrics.spacing_4;
                    padding: MaterialStyleMetrics.padding_4;
                    for cutoff[i] in root.bond_cutoffs: HorizontalLayout {
                        alignment: center;
                        spacing: MaterialStyleMetrics.spacing_4;
                        MaterialText {
                            text: cutoff.element1 + " - " + cutoff.element2 + ":";
                            vertical-alignment: center;
                            horizontal-stretch: 1;
                        }

                        TextField {
                            enabled: root.file_loaded;
                            text: cutoff.distance;
                            label: "Cutoff (Å)";
                            edited(s) => {
                                root.bond_cutoffs[i].distance = s;
                            }
                        }
                    }
                }
            }
        }
    }
}
