import {
    MaterialStyleMetrics,
    MaterialPalette,
    FilledCard,
    ExpandableHeader,
    TextField,
} from "@material";

export component RingsOptionsCard inherits FilledCard {
    in-out property <bool> expanded: false;
    in property <bool> file_loaded;
    in-out property <string> max_ring_size;

    property <length> md_height: root.expanded ? 50px : 0px;

    out property <string> hovered_tooltip_text:
        ring_size_area.has-hover ? "Maximum ring size to search for in topological motif analysis." : "";

    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_4;
        spacing: MaterialStyleMetrics.spacing_4;

        ExpandableHeader {
            text: "Topological Rings";
            expanded <=> root.expanded;
        }

        VerticalLayout {
            height: root.md_height;
            visible: self.height > 0.1px;
            opacity: root.expanded ? 1.0 : 0.0;
            animate height {
                duration: 250ms;
                easing: ease-in-out;
            }
            animate opacity {
                duration: 250ms;
                easing: ease-in-out;
            }
            spacing: MaterialStyleMetrics.spacing_8;
            padding_left: MaterialStyleMetrics.spacing_8;

            ring_size_area := TouchArea {
                TextField {
                    enabled: root.file_loaded;
                    width: 100%;
                    label: "Max Ring Size";
                    text <=> root.max_ring_size;
                }
            }
        }
    }
}
