// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialText } from "./material_text.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialTypography } from "../styling/material_typography.slint";

export component ToolTip {
    in property <string> text;
    in property <length> mouse_x;
    in property <length> mouse_y;
    in property <length> parent_width;
    in property <length> parent_height;

    x: root.mouse_x + self.width + 20px > root.parent_width ? root.mouse_x - self.width - 4px : root.mouse_x + 20px;
    y: root.mouse_y + self.height + 20px > root.parent_height ? root.mouse_y - self.height - 4px : root.mouse_y + 20px;

    z: 10000;

    background_layer := Rectangle {
        border_radius: 4px;
        background: MaterialPalette.inverse_surface;

        layout := VerticalLayout {
            padding_top: 4px;
            padding_bottom: 4px;
            padding_left: 8px;
            padding_right: 8px;

            MaterialText {
                text: root.text;
                max-width: 190px;
                vertical_alignment: center;
                horizontal_alignment: center;
                color: MaterialPalette.inverse_on_surface;
                style: MaterialTypography.body_medium;
                wrap: word-wrap;
                overflow: clip;
            }
        }
    }
}
