// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

export struct TextStyle {
    font_size: length,
    font_weight: int,
    letter_spacing: length,
}

export global MaterialTypography {
    out property <int> regular: 400;
    out property <int> medium: 500;
    out property <int> semibold: 600;

    out property <TextStyle> display_large: { font_size: 57px, font_weight: root.regular, letter_spacing: -0.25px };

    out property <TextStyle> display_medium: { font_size: 45px, font_weight: root.regular, letter_spacing: 0px };

    out property <TextStyle> display_small: { font_size: 36px, font_weight: root.regular, letter_spacing: 0px };

    out property <TextStyle> headline_large: { font_size: 32px, font_weight: root.regular, letter_spacing: 0px };

    out property <TextStyle> headline_medium: { font_size: 28px, font_weight: root.regular, letter_spacing: 0px };

    out property <TextStyle> headline_small: { font_size: 24px, font_weight: root.regular, letter_spacing: 0px };

    out property <TextStyle> title_large: { font_size: 22px, font_weight: root.semibold, letter_spacing: 0px };

    out property <TextStyle> title_medium: { font_size: 16px, font_weight: root.semibold, letter_spacing: 0.15px };

    out property <TextStyle> title_small: { font_size: 14px, font_weight: root.semibold, letter_spacing: 0.1px };

    out property <TextStyle> label_large: { font_size: 14px, font_weight: root.medium, letter_spacing: 0.1px };

    out property <TextStyle> label_large_prominent: { font_size: 14px, font_weight: root.semibold, letter_spacing: 0.1px };

    out property <TextStyle> label_medium: { font_size: 12px, font_weight: root.medium, letter_spacing: 0.5px };

    out property <TextStyle> label_medium_prominent: { font_size: 12px, font_weight: root.semibold, letter_spacing: 0.5px };

    out property <TextStyle> label_small: { font_size: 11px, font_weight: root.medium, letter_spacing: 0.5px };

    out property <TextStyle> body_large: { font_size: 14px, font_weight: root.regular, letter_spacing: 0.5px };

    out property <TextStyle> body_medium: { font_size: 12px, font_weight: root.regular, letter_spacing: 0.25px };

    out property <TextStyle> body_small: { font_size: 11px, font_weight: root.regular, letter_spacing: 0.4px };
}
