// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { Palette } from "std-widgets.slint";
import { MaterialSchemes, MaterialScheme } from "./material_schemes.slint";

export global MaterialPalette {
    out property <color> primary: root.scheme.primary;
    out property <color> surface_tint: root.scheme.surfaceTint;
    out property <color> on_primary: root.scheme.onPrimary;
    out property <color> primary_container: root.scheme.primaryContainer;
    out property <color> on_primary_container: root.scheme.onPrimaryContainer;
    out property <color> secondary: root.scheme.secondary;
    out property <color> on_secondary: root.scheme.onSecondary;
    out property <color> secondary_container: root.scheme.secondaryContainer;
    out property <color> on_secondary_container: root.scheme.onSecondaryContainer;
    out property <color> tertiary: root.scheme.tertiary;
    out property <color> on_tertiary: root.scheme.onTertiary;
    out property <color> tertiary_container: root.scheme.tertiaryContainer;
    out property <color> on_tertiary_container: root.scheme.onTertiaryContainer;
    out property <color> warning: root.scheme.warning;
    out property <color> on_warning: root.scheme.onWarning;
    out property <color> run: root.scheme.run;
    out property <color> on_run: root.scheme.onRun;
    out property <color> error: root.scheme.error;
    out property <color> on_error: root.scheme.onError;
    out property <color> error_container: root.scheme.errorContainer;
    out property <color> on_error_container: root.scheme.onErrorContainer;
    out property <color> background: root.scheme.background;
    out property <color> on_background: root.scheme.onBackground;
    out property <color> surface: root.scheme.surface;
    out property <color> on_surface: root.scheme.onSurface;
    out property <color> surface_variant: root.scheme.surfaceVariant;
    out property <color> on_surface_variant: root.scheme.onSurfaceVariant;
    out property <color> outline: root.scheme.outline;
    out property <color> outline_variant: root.scheme.outlineVariant;
    out property <color> shadow: root.scheme.shadow;
    out property <color> scrim: root.scheme.scrim;
    out property <color> inverse_surface: root.scheme.inverseSurface;
    out property <color> inverse_on_surface: root.scheme.inverseOnSurface;
    out property <color> inverse_primary: root.scheme.inversePrimary;
    out property <color> primary_fixed: root.scheme.primaryFixed;
    out property <color> on_primary_fixed: root.scheme.onPrimaryFixed;
    out property <color> primary_fixed_dim: root.scheme.primaryFixedDim;
    out property <color> on_primary_fixed_variant: root.scheme.onPrimaryFixedVariant;
    out property <color> secondary_fixed: root.scheme.secondaryFixed;
    out property <color> on_secondary_fixed: root.scheme.onSecondaryFixed;
    out property <color> secondary_fixed_dim: root.scheme.secondaryFixedDim;
    out property <color> on_secondary_fixed_variant: root.scheme.onSecondaryFixedVariant;
    out property <color> tertiary_fixed: root.scheme.tertiaryFixed;
    out property <color> on_tertiary_fixed: root.scheme.onTertiaryFixed;
    out property <color> tertiary_fixed_dim: root.scheme.tertiaryFixedDim;
    out property <color> on_tertiary_fixed_variant: root.scheme.onTertiaryFixedVariant;
    out property <color> surface_dim: root.scheme.surfaceDim;
    out property <color> surface_bright: root.scheme.surfaceBright;
    out property <color> surface_container_lowest: root.scheme.surfaceContainerLowest;
    out property <color> surface_container_low: root.scheme.surfaceContainerLow;
    out property <color> surface_container: root.scheme.surfaceContainer;
    out property <color> surface_container_high: root.scheme.surfaceContainerHigh;
    out property <color> surface_container_highest: root.scheme.surfaceContainerHighest;
    out property <color> shadow_15: #000000.with_alpha(15%);
    out property <color> shadow_30: #000000.with_alpha(30%);
    out property <float> state_layer_opacity_hover: 8%;
    out property <float> state_layer_opacity_focus: 10%;
    out property <float> state_layer_opacity_press: 10%;
    out property <float> state_layer_opacity_disabled: 12%;
    out property <float> state_layer_opacity_drag: 16%;
    out property <float> disable_opacity: 38%;
    out property <color> background_modal: #000000.with_alpha(50%);

    in property <MaterialSchemes> schemes: {
        light: {
            primary: rgb(68, 94, 145),
            surfaceTint: rgb(68, 94, 145),
            onPrimary: rgb(255, 255, 255),
            primaryContainer: rgb(216, 226, 255),
            onPrimaryContainer: rgb(0, 26, 66),
            secondary: rgb(87, 94, 113),
            onSecondary: rgb(255, 255, 255),
            secondaryContainer: rgb(219, 226, 249),
            onSecondaryContainer: rgb(20, 27, 44),
            tertiary: rgb(113, 85, 115),
            onTertiary: rgb(255, 255, 255),
            tertiaryContainer: rgb(252, 215, 251),
            onTertiaryContainer: rgb(41, 19, 45),
            warning: rgb(255, 235, 59),
            onWarning: rgb(62, 57, 0),
            run: rgb(129, 199, 132),
            onRun: rgb(0, 51, 0),
            error: rgb(244, 67, 54),
            onError: rgb(0, 0, 0),
            errorContainer: rgb(255, 218, 214),
            onErrorContainer: rgb(65, 0, 2),
            background: rgb(249, 249, 255),
            onBackground: rgb(26, 27, 32),
            surface: rgb(249, 249, 255),
            onSurface: rgb(26, 27, 32),
            surfaceVariant: rgb(225, 226, 236),
            onSurfaceVariant: rgb(68, 71, 79),
            outline: rgb(117, 119, 127),
            outlineVariant: rgb(196, 198, 208),
            shadow: rgb(0, 0, 0),
            scrim: rgb(0, 0, 0),
            inverseSurface: rgb(47, 48, 54),
            inverseOnSurface: rgb(240, 240, 247),
            inversePrimary: rgb(173, 198, 255),
            primaryFixed: rgb(216, 226, 255),
            onPrimaryFixed: rgb(0, 26, 66),
            primaryFixedDim: rgb(173, 198, 255),
            onPrimaryFixedVariant: rgb(43, 70, 120),
            secondaryFixed: rgb(219, 226, 249),
            onSecondaryFixed: rgb(20, 27, 44),
            secondaryFixedDim: rgb(191, 198, 220),
            onSecondaryFixedVariant: rgb(63, 71, 89),
            tertiaryFixed: rgb(252, 215, 251),
            onTertiaryFixed: rgb(41, 19, 45),
            tertiaryFixedDim: rgb(222, 188, 223),
            onTertiaryFixedVariant: rgb(88, 62, 91),
            surfaceDim: rgb(217, 217, 224),
            surfaceBright: rgb(246, 246, 255),
            surfaceContainerLowest: rgb(255, 255, 255),
            surfaceContainerLow: rgb(243, 243, 250),
            surfaceContainer: rgb(238, 237, 244),
            surfaceContainerHigh: rgb(232, 231, 239),
            surfaceContainerHighest: rgb(226, 226, 233),
        },
        dark: {
            primary: rgb(136, 192, 208),
            surfaceTint: rgb(136, 192, 208),
            onPrimary: rgb(16, 20, 25),
            primaryContainer: rgb(35, 55, 77),
            onPrimaryContainer: rgb(236, 239, 244),
            secondary: rgb(129, 161, 193),
            onSecondary: rgb(16, 20, 25),
            secondaryContainer: rgb(33, 46, 63),
            onSecondaryContainer: rgb(229, 233, 240),
            tertiary: rgb(143, 188, 187),
            onTertiary: rgb(16, 20, 25),
            tertiaryContainer: rgb(38, 54, 58),
            onTertiaryContainer: rgb(236, 239, 244),
            warning: rgb(235, 203, 139),
            onWarning: rgb(16, 20, 25),
            run: rgb(163, 190, 140),
            onRun: rgb(16, 20, 25),
            error: rgb(191, 97, 106),
            onError: rgb(16, 20, 25),
            errorContainer: rgb(191, 97, 106),
            onErrorContainer: rgb(236, 239, 244),
            background: rgb(16, 20, 25),
            onBackground: rgb(236, 239, 244),
            surface: rgb(16, 20, 25),
            onSurface: rgb(236, 239, 244),
            surfaceVariant: rgb(28, 35, 44),
            onSurfaceVariant: rgb(216, 222, 233),
            outline: rgb(59, 66, 82),
            outlineVariant: rgb(67, 76, 94),
            shadow: rgb(0, 0, 0),
            scrim: rgb(0, 0, 0),
            inverseSurface: rgb(236, 239, 244),
            inverseOnSurface: rgb(16, 20, 25),
            inversePrimary: rgb(35, 55, 77),
            primaryFixed: rgb(136, 192, 208),
            onPrimaryFixed: rgb(16, 20, 25),
            primaryFixedDim: rgb(129, 161, 193),
            onPrimaryFixedVariant: rgb(35, 55, 77),
            secondaryFixed: rgb(129, 161, 193),
            onSecondaryFixed: rgb(16, 20, 25),
            secondaryFixedDim: rgb(35, 55, 77),
            onSecondaryFixedVariant: rgb(28, 35, 44),
            tertiaryFixed: rgb(143, 188, 187),
            onTertiaryFixed: rgb(16, 20, 25),
            tertiaryFixedDim: rgb(129, 161, 193),
            onTertiaryFixedVariant: rgb(38, 54, 58),
            surfaceDim: rgb(10, 13, 16),
            surfaceBright: rgb(28, 35, 44),
            surfaceContainerLowest: rgb(7, 9, 11),
            surfaceContainerLow: rgb(16, 20, 25),
            surfaceContainer: rgb(22, 29, 36),
            surfaceContainerHigh: rgb(28, 35, 44),
            surfaceContainerHighest: rgb(36, 46, 57),
        },
    };

    property <MaterialScheme> scheme: Palette.color_scheme == ColorScheme.dark ? root.schemes.dark : root.schemes.light;
}
