// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

#include "core/Cell.hpp"
#include "math/Constants.hpp"
#include "math/LinearAlgebra.hpp"
#include "readers/FileReader.hpp"

#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <vector>

namespace {
class FileReaderTests : public ::testing::Test {
public:
  std::string data_dir_;

protected:
  static std::string getTestDataDir() {
    std::vector<std::string> const candidates = {
        "../../tests/data/", // build/tests -> tests/data
        "../tests/data/",    // build -> tests/data
        "tests/data/",       // project root
        "data/",             // if cwd is tests
    };
    for (const auto &dir : candidates) {
      if (std::filesystem::exists(dir + "vasp/POSCAR")) {
        return dir;
      }
    }
    return "../../tests/data/";
  }

  void SetUp() override { data_dir_ = getTestDataDir(); }
};
} // namespace

TEST_F(FileReaderTests, ReadCarFileCorrectly) {
  std::string const path = data_dir_ + "car/test.car";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  // Assert: Check lattice parameters
  const auto &params = result_cell.lattice_parameters();
  EXPECT_DOUBLE_EQ(params[0], 10.5);
  EXPECT_DOUBLE_EQ(params[1], 11.5);
  EXPECT_DOUBLE_EQ(params[2], 12.5);
  EXPECT_DOUBLE_EQ(params[3], 90.0);
  EXPECT_DOUBLE_EQ(params[4], 90.0);
  EXPECT_DOUBLE_EQ(params[5], 90.0);

  // Assert: Check atoms
  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  EXPECT_EQ(atoms[0].element().symbol, "C");
  EXPECT_DOUBLE_EQ(atoms[0].position().x(), 1.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().y(), 2.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().z(), 3.0);

  EXPECT_EQ(atoms[1].element().symbol, "Si");
  EXPECT_DOUBLE_EQ(atoms[1].position().x(), 4.5);
  EXPECT_DOUBLE_EQ(atoms[1].position().y(), 5.5);
  EXPECT_DOUBLE_EQ(atoms[1].position().z(), 6.5);
}

TEST_F(FileReaderTests, ReadCellFileCorrectly) {
  std::string const path = data_dir_ + "cell/test.cell";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  // Assert: Check lattice parameters
  const auto &params = result_cell.lattice_parameters();
  EXPECT_THAT(params[0], correlation::testing::IsRealEq(15.0));  // a
  EXPECT_THAT(params[1], correlation::testing::IsRealEq(15.0));  // b
  EXPECT_THAT(params[2], correlation::testing::IsRealEq(20.0));  // c
  EXPECT_THAT(params[3], correlation::testing::IsRealEq(90.0));  // alpha
  EXPECT_THAT(params[4], correlation::testing::IsRealEq(90.0));  // beta
  EXPECT_THAT(params[5], correlation::testing::IsRealEq(120.0)); // gamma

  // Assert: Check atoms
  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  EXPECT_EQ(atoms[0].element().symbol, "C");
  EXPECT_THAT(atoms[0].position().x(), correlation::testing::IsRealEq(1.1));
  EXPECT_THAT(atoms[0].position().y(), correlation::testing::IsRealEq(2.2));
  EXPECT_THAT(atoms[0].position().z(), correlation::testing::IsRealEq(3.3));

  EXPECT_EQ(atoms[1].element().symbol, "O");
  EXPECT_THAT(atoms[1].position().x(), correlation::testing::IsRealEq(4.4));
  EXPECT_THAT(atoms[1].position().y(), correlation::testing::IsRealEq(5.5));
  EXPECT_THAT(atoms[1].position().z(), correlation::testing::IsRealEq(6.6));
}

TEST_F(FileReaderTests, ReadCifFileCorrectly) {
  std::string const path = data_dir_ + "cif/test.cif";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  // Assert: Check lattice parameters
  const auto &params = result_cell.lattice_parameters();
  EXPECT_THAT(params[0], correlation::testing::IsRealEq(5.64)); // a
  EXPECT_THAT(params[1], correlation::testing::IsRealEq(5.64)); // b
  EXPECT_THAT(params[2], correlation::testing::IsRealEq(5.64)); // c
  EXPECT_THAT(params[5], correlation::testing::IsRealEq(90.0)); // gamma

  // Assert: Check total atom count (2 unique atoms * 1 symm ops = 2 atoms)
  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  // Assert: Check that specific, expected atoms were generated by symmetry
  bool na_origin_found = false;
  bool cl_center_found = false;
  for (const auto &atom : atoms) {
    if (atom.element().symbol == "Na" && correlation::math::norm(atom.position()) < 1e-4) {
      na_origin_found = true;
    }
    correlation::math::Vector3R expected_cl_pos = {2.82, 2.82, 2.82};
    if (atom.element().symbol == "Cl" && correlation::math::norm(atom.position() - expected_cl_pos) < 1e-4) {
      cl_center_found = true;
    }
  }
  EXPECT_TRUE(na_origin_found) << "Did not find the original Na atom at (0,0,0)";
  EXPECT_TRUE(cl_center_found) << "Did not find the original Cl atom at the cell center";
}

TEST_F(FileReaderTests, ReadArcFileCorrectly) {
  std::string const path = data_dir_ + "arc/test.arc";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  EXPECT_EQ(type, correlation::readers::FileType::Arc);

  correlation::core::Trajectory traj = correlation::readers::readTrajectory(path, type);

  const auto &frames = traj.getFrames();
  ASSERT_EQ(frames.size(), 2);

  // Check Frame 1
  const auto &file_1 = frames[0];
  EXPECT_DOUBLE_EQ(file_1.lattice_parameters()[0], 10.0);
  ASSERT_EQ(file_1.atomCount(), 1);
  EXPECT_DOUBLE_EQ(file_1.atoms()[0].position().x(), 1.0);

  // Check Frame 2
  const auto &file_2 = frames[1];
  EXPECT_DOUBLE_EQ(file_2.lattice_parameters()[0], 11.0);
  ASSERT_EQ(file_2.atomCount(), 1);
  EXPECT_DOUBLE_EQ(file_2.atoms()[0].position().x(), 2.0);
}

TEST_F(FileReaderTests, ReadArcFileDuplicatedFrames) {
  std::string const path = data_dir_ + "arc/test_identical.arc";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  EXPECT_EQ(type, correlation::readers::FileType::Arc);

  correlation::core::Trajectory traj = correlation::readers::readTrajectory(path, type);

  const auto &frames = traj.getFrames();
  ASSERT_EQ(frames.size(), 2);

  // Check Frame 1
  EXPECT_DOUBLE_EQ(frames[0].lattice_parameters()[0], 10.0);
  EXPECT_DOUBLE_EQ(frames[0].atoms()[0].position().x(), 1.0);

  // Check Frame 2
  EXPECT_DOUBLE_EQ(frames[1].lattice_parameters()[0], 11.0);
  EXPECT_DOUBLE_EQ(frames[1].atoms()[0].position().x(), 2.0);
}

TEST_F(FileReaderTests, ReadLammpsDumpCorrectly) {
  std::string const path = data_dir_ + "lammps/test.dump";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  // Assert: Check lattice parameters
  const auto &params = result_cell.lattice_parameters();
  EXPECT_DOUBLE_EQ(params[0], 10.0);
  EXPECT_DOUBLE_EQ(params[1], 11.0);
  EXPECT_DOUBLE_EQ(params[2], 12.0);

  // Assert: Check atoms
  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  EXPECT_EQ(atoms[0].element().symbol, "1");
  EXPECT_DOUBLE_EQ(atoms[0].position().x(), 1.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().y(), 2.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().z(), 3.0);

  EXPECT_EQ(atoms[1].element().symbol, "2");
  EXPECT_DOUBLE_EQ(atoms[1].position().x(), 4.0);
  EXPECT_DOUBLE_EQ(atoms[1].position().y(), 5.0);
  EXPECT_DOUBLE_EQ(atoms[1].position().z(), 6.0);
}

TEST_F(FileReaderTests, ReadLammpsDumpTrajectoryCorrectly) {
  std::string const path = data_dir_ + "lammps/test_multi.dump";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  EXPECT_EQ(type, correlation::readers::FileType::LammpsDump);

  correlation::core::Trajectory traj = correlation::readers::readTrajectory(path, type);
  const auto &frames = traj.getFrames();
  ASSERT_EQ(frames.size(), 2);

  // Frame 1 positions
  const auto &file_1 = frames[0];
  ASSERT_EQ(file_1.atomCount(), 2);
  EXPECT_DOUBLE_EQ(file_1.atoms()[0].position().x(), 1.0);
  EXPECT_DOUBLE_EQ(file_1.atoms()[1].position().x(), 4.0);

  // Frame 2 positions
  const auto &file_2 = frames[1];
  ASSERT_EQ(file_2.atomCount(), 2);
  EXPECT_DOUBLE_EQ(file_2.atoms()[0].position().x(), 1.5);
  EXPECT_DOUBLE_EQ(file_2.atoms()[1].position().x(), 4.5);
}

TEST_F(FileReaderTests, ReadLammpsDumpElementColumnCorrectly) {
  std::string const path = data_dir_ + "lammps/test_element.dump";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  EXPECT_EQ(type, correlation::readers::FileType::LammpsDump);

  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  EXPECT_EQ(atoms[0].element().symbol, "Si");
  EXPECT_DOUBLE_EQ(atoms[0].position().x(), 1.0);

  EXPECT_EQ(atoms[1].element().symbol, "O");
  EXPECT_DOUBLE_EQ(atoms[1].position().x(), 4.0);
}

TEST_F(FileReaderTests, ReadOnetepDatCorrectly) {
  std::string const path = data_dir_ + "onetep_dat/test.dat";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  correlation::core::Cell result_cell = correlation::readers::readStructure(path, type);

  // Assert: Check lattice parameters
  const auto &params = result_cell.lattice_parameters();
  EXPECT_DOUBLE_EQ(params[0], 10.0);
  EXPECT_DOUBLE_EQ(params[1], 11.0);
  EXPECT_DOUBLE_EQ(params[2], 12.0);

  // Assert: Check atoms
  const auto &atoms = result_cell.atoms();
  ASSERT_EQ(atoms.size(), 2);

  EXPECT_EQ(atoms[0].element().symbol, "C");
  EXPECT_DOUBLE_EQ(atoms[0].position().x(), 1.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().y(), 2.0);
  EXPECT_DOUBLE_EQ(atoms[0].position().z(), 3.0);

  EXPECT_EQ(atoms[1].element().symbol, "Si");
  EXPECT_DOUBLE_EQ(atoms[1].position().x(), 4.5);
  EXPECT_DOUBLE_EQ(atoms[1].position().y(), 5.5);
  EXPECT_DOUBLE_EQ(atoms[1].position().z(), 6.5);
}

TEST_F(FileReaderTests, ReadCastepMdCorrectly) {
  std::string const path = data_dir_ + "castep_md/test.md";
  correlation::readers::FileType type = correlation::readers::determineFileType(path);
  EXPECT_EQ(type, correlation::readers::FileType::CastepMd);

  correlation::core::Trajectory traj = correlation::readers::readTrajectory(path, type);

  const auto &frames = traj.getFrames();
  ASSERT_EQ(frames.size(), 2);

  // Check Frame 1
  const auto &file_1 = frames[0];
  EXPECT_THAT(file_1.lattice_parameters()[0],
              correlation::testing::IsRealEq(10.0 * correlation::math::bohr_to_angstrom));
  EXPECT_THAT(file_1.lattice_parameters()[1],
              correlation::testing::IsRealEq(11.0 * correlation::math::bohr_to_angstrom));
  EXPECT_THAT(file_1.lattice_parameters()[2],
              correlation::testing::IsRealEq(12.0 * correlation::math::bohr_to_angstrom));
  ASSERT_EQ(file_1.atomCount(), 2);
  EXPECT_THAT(file_1.atoms()[0].position().x(),
              correlation::testing::IsRealEq(1.0 * correlation::math::bohr_to_angstrom));
  EXPECT_THAT(file_1.atoms()[1].position().x(),
              correlation::testing::IsRealEq(4.0 * correlation::math::bohr_to_angstrom));

  EXPECT_THAT(file_1.getEnergy(), correlation::testing::IsRealEq(-31.8206146));

  // Check Frame 2
  const auto &file_2 = frames[1];
  EXPECT_THAT(file_2.lattice_parameters()[0],
              correlation::testing::IsRealEq(10.0 * correlation::math::bohr_to_angstrom));
  EXPECT_THAT(file_2.atoms()[0].position().x(),
              correlation::testing::IsRealEq(1.1 * correlation::math::bohr_to_angstrom));
}

TEST_F(FileReaderTests, ReadCelluloseExample) {
  std::string cellulose_path = "../../examples/Cellulose/Cellulose.md";
  std::ifstream file(cellulose_path);
  if (!file.good()) {
    cellulose_path = "../examples/Cellulose/Cellulose.md";
    std::ifstream file2(cellulose_path);
    if (!file2.good()) {
      cellulose_path = "examples/Cellulose/Cellulose.md";
      std::ifstream file3(cellulose_path);
      if (!file3.good()) {
        GTEST_SKIP() << "Cellulose.md example file not found. Skipping test.";
        return;
      }
    }
  }

  correlation::readers::FileType type = correlation::readers::determineFileType(cellulose_path);
  EXPECT_EQ(type, correlation::readers::FileType::CastepMd);

  correlation::core::Trajectory traj = correlation::readers::readTrajectory(cellulose_path, type);
  const auto &frames = traj.getFrames();

  EXPECT_EQ(frames.size(), 1001);
  if (!frames.empty()) {
    EXPECT_GT(frames[0].atomCount(), 0);
  }
}

TEST_F(FileReaderTests, ReadOutmolCorrectly) {
  std::string file_path = "../../examples/PdCuNiP/PdCuNiP.outmol";
  std::ifstream file(file_path);
  if (!file.good()) {
    file_path = "../examples/PdCuNiP/PdCuNiP.outmol";
    std::ifstream file2(file_path);
    if (!file2.good()) {
      file_path = "examples/PdCuNiP/PdCuNiP.outmol";
      std::ifstream file3(file_path);
      if (!file3.good()) {
        GTEST_SKIP() << "PdCuNiP.outmol example file not found. Skipping test.";
        return;
      }
    }
  }

  correlation::core::Trajectory traj =
      correlation::readers::readTrajectory(file_path, correlation::readers::FileType::Outmol);
  const auto &frames = traj.getFrames();

  EXPECT_GT(frames.size(), 0);
  EXPECT_GT(frames.size(), 200);

  if (!frames.empty()) {
    const correlation::core::Cell &frame0 = frames[0];
    EXPECT_EQ(frame0.atomCount(), 216);

    EXPECT_NEAR(frame0.lattice_parameters()[0], 14.172, 1e-3);
    EXPECT_NEAR(frame0.lattice_parameters()[1], 14.172, 1e-3);
    EXPECT_NEAR(frame0.lattice_parameters()[2], 14.172, 1e-3);
  }
}

TEST_F(FileReaderTests, DetermineFileTypeExtensionlessVasp) {
  using correlation::readers::determineFileType;
  using correlation::readers::FileType;

  EXPECT_EQ(determineFileType("POSCAR"), FileType::Vasp);
  EXPECT_EQ(determineFileType("CONTCAR"), FileType::Vasp);
  EXPECT_EQ(determineFileType("XDATCAR"), FileType::Xdatcar);

  EXPECT_EQ(determineFileType("poscar"), FileType::Vasp);
  EXPECT_EQ(determineFileType("contcar"), FileType::Vasp);
  EXPECT_EQ(determineFileType("xdatcar"), FileType::Xdatcar);

  EXPECT_EQ(determineFileType("PosCar"), FileType::Vasp);
  EXPECT_EQ(determineFileType("XdatCar"), FileType::Xdatcar);

  EXPECT_EQ(determineFileType("/path/to/POSCAR"), FileType::Vasp);
  EXPECT_EQ(determineFileType("relative/path/CONTCAR"), FileType::Vasp);
  EXPECT_EQ(determineFileType("./XDATCAR"), FileType::Xdatcar);
}

TEST_F(FileReaderTests, ReadExtensionlessVaspStructure) {
  using correlation::readers::FileType;
  using correlation::readers::readStructure;

  correlation::core::Cell poscar_cell = readStructure(data_dir_ + "vasp/POSCAR", FileType::Vasp);
  EXPECT_EQ(poscar_cell.atomCount(), 2);
  EXPECT_NEAR(poscar_cell.lattice_parameters()[0], 5.43, 1e-6);

  correlation::core::Cell contcar_cell = readStructure(data_dir_ + "vasp/CONTCAR", FileType::Vasp);
  EXPECT_EQ(contcar_cell.atomCount(), 2);
  EXPECT_NEAR(contcar_cell.lattice_parameters()[0], 5.43, 1e-6);
}

TEST_F(FileReaderTests, ReadExtensionlessVaspTrajectory) {
  using correlation::readers::FileType;
  using correlation::readers::readTrajectory;

  correlation::core::Trajectory traj = readTrajectory(data_dir_ + "xdatcar/XDATCAR", FileType::Xdatcar);
  EXPECT_EQ(traj.getFrameCount(), 2);

  const auto &file_1 = traj.getFrame(0);
  EXPECT_EQ(file_1.atomCount(), 2);
  EXPECT_NEAR(file_1.lattice_parameters()[0], 5.43, 1e-6);
}
