// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialStyleMetrics,
    MaterialPalette,
    OutlinedCard,
    ExpandableHeader,
    DropDownMenu,
    Vertical,
} from "../../material/material.slint";

export component MaterialTypeCard inherits OutlinedCard {
    in-out property <bool> expanded: true;
    in property <bool> file_loaded;
    in-out property <int> material_type: 0; // 0: Amorphous, 1: Liquid, 2: Crystalline
    callback reset();

    out property <string> hovered_tooltip_text:
        material_dropdown_area.has-hover ? "Select the material type to load recommended parameter defaults." : "";

    out property <length> hovered_x:
        material_dropdown_area.has-hover ? material_dropdown_area.absolute-position.x + material_dropdown_area.mouse-x : 0px;
    out property <length> hovered_y:
        material_dropdown_area.has-hover ? material_dropdown_area.absolute-position.y + material_dropdown_area.mouse-y : 0px;
    out property <length> hovered_width: 0px;
    out property <length> hovered_height: 0px;

    Vertical {
        padding: MaterialStyleMetrics.spacing_8;
        spacing: MaterialStyleMetrics.spacing_8;

        ExpandableHeader {
            text: "Material Type";
            expanded <=> root.expanded;
            show_reset: true;
            reset_enabled: root.file_loaded;
            reset => { root.reset(); }
        }

        Vertical {
            height: root.expanded ? self.preferred-height : 0px;
            visible: self.height > 0px;
            opacity: root.expanded ? 1.0 : 0.0;
            animate height, opacity {
                duration: 250ms;
                easing: ease-in-out;
            }

            padding: 0;
            spacing: MaterialStyleMetrics.spacing_8;

            material_dropdown_area := TouchArea {
                DropDownMenu {
                    width: 100%;
                    label: "Material Defaults";
                    enabled: root.file_loaded;
                    items: [
                        { text: "Amorphous", enabled: true },
                        { text: "Liquid", enabled: true },
                        { text: "Crystalline", enabled: true }
                    ];
                    current_index <=> root.material_type;
                }
            }
        }
    }
}
