import { ToolTip } from "material/material.slint";

// ============================================================================
// AppToolTips Component
// ============================================================================
/// Manages tooltips displayed across the application.
// ============================================================================
export component AppToolTips inherits Rectangle {
    in property <length> hovered_x;
    in property <length> hovered_y;
    in property <length> hovered_width;
    in property <length> hovered_height;
    background: transparent;
    
    // Hover text to display
    in property <string> hovered_tooltip_text: "";

    ToolTip {
        hovered_x: root.hovered_x;
        hovered_y: root.hovered_y;
        hovered_width: root.hovered_width;
        hovered_height: root.hovered_height;
        parent_width: root.width;
        parent_height: root.height;
        visible: root.hovered_tooltip_text != "";
        text: root.hovered_tooltip_text;
    }
}
