import {
    MaterialPalette,
    MaterialStyleMetrics,
    MaterialTypography,
    FilledButton,
    CheckBoxTile,
    CheckState,
    TextField,
    DropDownMenu,
    MenuItem,
    OutlinedCard,
    MaterialText,
    ToolTip,
} from "../material-1.0/material.slint";


export component AppWindow inherits Window {
    // Callback that the UI invokes on the C++ side
    callback run_analysis();
    callback browse_file();
    callback check_file_dialog_status();

    // Properties that C++ updates to change the UI
    in-out property <string> file_status_text: "Please load a structure file.";
    in-out property <string> analysis_status_text: "";
    in-out property <float> progress: 0.0;
    in-out property <bool> analysis_running: false;
    in-out property <bool> timer_running: false;
    in-out property <bool> text_opacity: true;

    // User-configurable options
    in-out property <string> in_file_text;
    in-out property <bool> normalize;
    in-out property <bool> smoothing;
    in-out property <string> r_max;
    in-out property <string> r_bin_width;
    in-out property <string> q_max;
    in-out property <string> q_bin_width;
    in-out property <string> r_int_max;
    in-out property <string> angle_max;
    in-out property <string> angle_bin_width;
    in-out property <string> bond_factor;
    in-out property <string> smoothing_sigma;
    in-out property <int> smoothing_kernel;

    preferred-width: 650px;
    preferred-height: 750px;
    background: MaterialPalette.background;
    default-font-size: MaterialTypography.body_small.font_size;
    default-font-weight: MaterialTypography.body_small.font_weight;
    property <image> logo-icon: @image-url("../Images/Logo.png");
    icon: logo-icon;
    title: "Correlation Analysis Tool";

    timer := Timer {
        interval: 200ms;
        running: timer_running;
        triggered() => {
            check_file_dialog_status();
        }
    }

    window_area := TouchArea {
        VerticalLayout {
            padding: MaterialStyleMetrics.padding_16;
            spacing: MaterialStyleMetrics.spacing_16;

            OutlinedCard {
                VerticalLayout {
                    padding: MaterialStyleMetrics.padding_16;
                    spacing: MaterialStyleMetrics.spacing_12;
                    MaterialText {
                        text: "1. Input File";
                        style: MaterialTypography.title_medium;
                    }

                    file_area := TouchArea {
                        min-height: 50px;
                        FilledButton {
                            height: 100%;
                            width: 100%;
                            text: "Load a structure file";
                            clicked => {
                                browse_file();
                            }
                        }
                    }

                    Text {
                        text: file_status_text;
                        color: MaterialPalette.on_surface;
                        wrap: word-wrap;
                    }
                }
            }

            OutlinedCard {
                VerticalLayout {
                    padding: MaterialStyleMetrics.padding_16;
                    spacing: MaterialStyleMetrics.spacing_12;
                    MaterialText {
                        text: "2. Options";
                        style: MaterialTypography.title_medium;
                    }

                    HorizontalLayout {
                        spacing: MaterialStyleMetrics.spacing_8;
                        r_max_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "RDF Max r (Å)";
                                text <=> r_max;
                            }
                        }

                        r_bin_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "RDF Bin Width (Å)";
                                text <=> r_bin_width;
                            }
                        }

                        bond_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "Bond Parameter";
                                text <=> bond_factor;
                            }
                        }
                    }

                    HorizontalLayout {
                        spacing: MaterialStyleMetrics.spacing_8;
                        theta_max_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "PAD Max Angle (°)";
                                text <=> angle_max;
                            }
                        }

                        theta_bin_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "PAD Bin Width (°)";
                                text <=> angle_bin_width;
                            }
                        }
                    }

                    HorizontalLayout {
                        spacing: MaterialStyleMetrics.spacing_8;
                        s_max_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "Max Q (Å⁻¹)";
                                text <=> q_max;
                            }
                        }

                        s_bin_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "S(Q) Bin Width (Å⁻¹)";
                                text: q_bin_width;
                                edited(s) => {
                                    q_bin_width = s;
                                }
                            }
                        }

                        r_int_area := TouchArea {
                            horizontal-stretch: 1;
                            TextField {
                                width: 100%;
                                label: "Max r for the FFT (Å)";
                                text: r_int_max;
                                edited(s) => {
                                    r_int_max = s;
                                }
                            }
                        }
                    }

                    HorizontalLayout {
                        spacing: MaterialStyleMetrics.spacing_8;

                        smooth_area := TouchArea {
                            CheckBoxTile {
                                text: "Enable Smoothing";
                                check_state: smoothing ? CheckState.checked : CheckState.unchecked;
                                checked_state_changed(s) => {
                                    smoothing = (s == CheckState.checked);
                                }
                            }
                        }

                        sigma_area := TouchArea {
                            TextField {
                                width: 100%;
                                label: "Smoothing Sigma";
                                enabled: smoothing;
                                text <=> smoothing_sigma;
                            }
                        }

                        kernel_area := TouchArea {
                            DropDownMenu {
                                width: 100%;
                                enabled: smoothing;
                                label: "Smoothing Kernel";
                                items: [
                                    { text: "Gaussian", enabled: true },
                                    { text: "Bump", enabled: true },
                                    { text: "Triweight", enabled: true }
                                ];
                                current-index <=> smoothing_kernel;
                            }
                        }
                    }
                }
            }

            OutlinedCard {
                VerticalLayout {
                    padding: MaterialStyleMetrics.padding_16;
                    spacing: MaterialStyleMetrics.spacing_12;
                    MaterialText {
                        text: "3. Run Analysis";
                        style: MaterialTypography.title_medium;
                    }

                    analysis_area := TouchArea {
                        min-height: 50px;
                        FilledButton {
                            height: 100%;
                            width: 100%;
                            text: analysis_running ? "Analysis in Progress..." : "Run Analysis";
                            enabled: !analysis_running;
                            clicked => {
                                analysis_status_text = "Running Analysis...";
                                run_analysis();
                                analysis_status_text = "Analysis ended.";
                            }
                        }
                    }

                    Text {
                        text: analysis_status_text;
                        color: MaterialPalette.on_surface;
                        wrap: word-wrap;
                    }
                }
            }
        }
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Load a structure file";
        visible: file_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Maximum radius to calculate Radial Distribution Functions (g(r), J(r), G(r)). The recommended max radius is 20 Å.";
        visible: r_max_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Bin width used to calculate the histograms for the Radial Distribution Functions (g(r), J(r), G(r)). The recommended bin is 0.02 Å.";
        visible: r_bin_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x - 235px;
        y: window_area.mouse_y + 20px;
        text: "Bond factor used to determine if two atoms are bonded. The bond parameter is calculated as follows: b = (max_bond_distance)/ (sum_of_covalent_radii). The default bond parameter is 1.2.";
        visible: bond_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Maximum angle to calculate the Plane-Angle Distribution (F(θ)). The recommended max angle is 180°.";
        visible: theta_max_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x - 190px;
        y: window_area.mouse_y + 20px;
        text: "Bin width used to calculate the histograms for the Plane-Angle Distribution. The recommended bin is 1.0°.";
        visible: theta_bin_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Maximum scattering vector (Q) to calculate the Structure Factor (S(Q)). The recommended max scattering vector is 20.0 Å⁻¹";
        visible: s_max_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Bin width used to calculate the histograms for the Structure Factor. The recommended bin is 0.02 Å⁻¹.";
        visible: s_bin_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x - 215px;
        y: window_area.mouse_y + 20px;
        text: "Maximum radius for the Fourier Transform of the g(r) used to calculate the Structure Factor. The recommended max radius is 10.0 Å";
        visible: r_int_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Enable the smoothing of the distribution functions.";
        visible: smooth_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x + 20px;
        y: window_area.mouse_y + 20px;
        text: "Sigma to be used for the smoothing of the distribution functions. The recommended  sigma is 0.01.";
        visible: sigma_area.has-hover;
    }

    ToolTip {
        x: window_area.mouse_x - 270px;
        y: window_area.mouse_y + 20px;
        text: "The kernel used by the kernel smoother. The recommended kernel is the Gaussian kernel.";
        visible: kernel_area.has-hover;
    }
}
