// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialStyleMetrics,
    MaterialTypography,
    TextField,
    OutlinedCard,
    MaterialText,
} from "@material";
import { BondCutoff } from "Types.slint";

export component BondCutoffsCard inherits OutlinedCard {
    in property <bool> file_loaded;
    in-out property <[BondCutoff]> bond_cutoffs;

    VerticalLayout {
        padding: MaterialStyleMetrics.padding_4;
        spacing: MaterialStyleMetrics.spacing_4;
        MaterialText {
            text: "3. Bond Cutoffs (Å)";
            style: MaterialTypography.title_small;
        }

        VerticalLayout {
            spacing: MaterialStyleMetrics.spacing_4;
            for cutoff[i] in root.bond_cutoffs: HorizontalLayout {
                alignment: center;
                spacing: MaterialStyleMetrics.spacing_4;
                MaterialText {
                    min-width: 80px;
                    text: cutoff.element1 + " - " + cutoff.element2 + ":";
                    vertical-alignment: center;
                    horizontal-stretch: 1;
                }

                TextField {
                    enabled: root.file_loaded;
                    min-width: 100px;
                    text: cutoff.distance;
                    label: "Cutoff (Å)";
                    edited(s) => {
                        root.bond_cutoffs[i].distance = s;
                    }
                }
            }
        }
    }
}
