// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialStyleMetrics,
    MaterialTypography,
    MaterialPalette,
    OutlinedCard,
    MaterialText,
} from "@material";
import { AtomCount } from "Types.slint";

export component FileInfoCard inherits OutlinedCard {
    in-out property <string> file_status_text;
    in property <bool> file_loaded;
    in property <int> num_frames;
    in property <int> total_atoms;
    in property <int> removed_frames_count;
    in property <[AtomCount]> atom_counts;
    in-out property <string> time_step;

    opacity: root.file_loaded ? 1.0 : 0.5;
    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_8;
        spacing: MaterialStyleMetrics.spacing_4;
        MaterialText {
            text: "2. File Info";
            style: MaterialTypography.title_small;
        }

        VerticalLayout {
            spacing: MaterialStyleMetrics.spacing_4;

            MaterialText {
                text: root.file_status_text;
                horizontal-stretch: 1;
                wrap: word-wrap;
            }

            HorizontalLayout {
                MaterialText {
                    text: "Frames:";
                    horizontal-stretch: 1;
                }

                MaterialText {
                    text: root.num_frames;
                    horizontal-alignment: right;
                }
            }

            HorizontalLayout {
                MaterialText {
                    text: "Total Atoms:";
                    horizontal-stretch: 1;
                }

                MaterialText {
                    text: root.total_atoms;
                    horizontal-alignment: right;
                }
            }

            if (root.removed_frames_count > 0): HorizontalLayout {
                MaterialText {
                    text: "Removed Frames:";
                    horizontal-stretch: 1;
                    color: MaterialPalette.error;
                }

                MaterialText {
                    text: root.removed_frames_count;
                    horizontal-alignment: right;
                    color: MaterialPalette.error;
                }
            }

            Rectangle {
                height: 1px;
                background: MaterialPalette.outline_variant;
            }

            for info in root.atom_counts: HorizontalLayout {
                MaterialText {
                    text: info.symbol + ":";
                    horizontal-stretch: 1;
                }

                MaterialText {
                    text: info.count;
                    horizontal-alignment: right;
                }
            }
        }
    }
}
