// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2025 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { VerticalBox, LineEdit } from "std-widgets.slint";

export component InputGroup inherits TouchArea {
    // Input properties
    in property <string> label_text;
    in-out property <string> value_text;
    in property <string> unit_text: "";
    in property <bool> enabled_input;

    VerticalBox {
        Text {
            text: label_text + (root.unit_text != "" ? " (" + root.unit_text + ")" : "");
        }

        LineEdit {
            enabled: enabled_input;
            text: value_text;
            edited(s) => {
                value_text = s;
            }
        }
    }
}
