// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialStyleMetrics,
    MaterialTypography,
    FilledButton,
    OutlinedCard,
    MaterialText,
} from "@material";

export component InputFileCard inherits OutlinedCard {
    callback browse_file();
    
    // Export hover state for tooltip
    out property <bool> file_area_has_hover: file_area.has-hover;
    in property <bool> enabled: true;

    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_8;
        spacing: MaterialStyleMetrics.spacing_4;
        MaterialText {
            text: "Input File";
            style: MaterialTypography.title_small;
        }

        file_area := TouchArea {
            min-height: 40px;
            FilledButton {
                enabled: root.enabled;
                height: 40px;
                width: 100%;
                text: "Load structure file";
                clicked => {
                    root.browse_file();
                }
            }
        }
    }
}
