// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialPalette,
    MaterialStyleMetrics,
    MaterialTypography,
    FilledButton,
    FilledCard,
    MaterialText,
    CheckBox,
    CheckState,
    TextField,
    LinearProgressIndicator,
    Icons,
    Icon,
    CheckBoxRow,
} from "@material";
import { FileInfoCard } from "FileInfoCard.slint";

export component RunAnalysisCard inherits FilledCard {
    in property <bool> file_loaded;
    in property <bool> analysis_running;
    in property <bool> analysis_done;
    in property <float> progress;
    in-out property <string> analysis_status_text;
    in-out property <bool> use_csv: true;
    in-out property <bool> use_hdf5: true;
    in-out property <string> min_frame;
    in-out property <string> max_frame;
    in-out property <bool> advanced_options_visible;
    callback run_analysis();
    callback write_files();
    callback options_toggled(bool);

    // Hover state for tooltip
    out property <bool> analysis_area_has_hover: analysis_area.has-hover;
    out property <bool> hdf5_area_has_hover: hdf5_area.has-hover;
    out property <bool> csv_area_has_hover: csv_area.has-hover;
    out property <bool> options_area_has_hover: options_area.has-hover;
    out property <bool> start_frame_has_hover: start_frame_area.has-hover;
    out property <bool> end_frame_has_hover: end_frame_area.has-hover;
    out property <bool> write_area_has_hover: write_area.has-hover;

    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_8;
        spacing: MaterialStyleMetrics.spacing_4;

        options_area := TouchArea {
            width: 100%;
            height: 40px;
            mouse-cursor: pointer;
            clicked => {
                root.advanced_options_visible = !root.advanced_options_visible;
                root.options_toggled(root.advanced_options_visible);
            }
            Rectangle {
                background: MaterialPalette.warning;
                border-radius: MaterialStyleMetrics.border_radius_8;
                HorizontalLayout {
                    alignment: center;
                    spacing: 8px;
                    padding-left: 16px;
                    padding-right: 16px;
                    MaterialText {
                        text: "Options";
                        vertical-alignment: center;
                        color: MaterialPalette.on_warning;
                        style: MaterialTypography.label_large;
                    }

                    Icon {
                        y: 8px;
                        source: root.advanced_options_visible ? Icons.arrow_left : Icons.arrow_right;
                        width: 25px;
                        height: 25px;
                        vertical-alignment: center;
                        colorize: MaterialPalette.on_warning;
                    }
                }
            }
        }

        // Frame Range
        MaterialText {
            text: "Frame Range";
            style: MaterialTypography.label_large;
            color: MaterialPalette.on_surface_variant;
        }

        HorizontalLayout {
            spacing: MaterialStyleMetrics.spacing_4;

            start_frame_area := TouchArea {
                start_frame := TextField {
                    enabled: root.file_loaded;
                    width: 100%;
                    label: "Start Frame";
                    text <=> root.min_frame;
                }
            }

            end_frame_area := TouchArea {
                end_frame := TextField {
                    enabled: root.file_loaded;
                    width: 100%;
                    label: "End Frame";
                    text <=> root.max_frame;
                }
            }
        }

        // Export Options
        MaterialText {
            text: "Export Formats";
            style: MaterialTypography.label_large;
            color: MaterialPalette.on_surface_variant;
        }

        csv_area := CheckBoxRow {
            enabled: root.file_loaded;
            check_state_bool: root.use_csv;
            text: "Export as CSV";
            checked_state_changed(s) => {
                root.use_csv = s;
            }
        }

        hdf5_area := CheckBoxRow {
            enabled: root.file_loaded;
            check_state_bool: root.use_hdf5;
            text: "Export as HDF5";
            checked_state_changed(s) => {
                root.use_hdf5 = s;
            }
        }

        // Main Action Button
        analysis_area := TouchArea {
            FilledButton {
                width: 100%;
                text: root.analysis_running ? "In Progress..." : "Run Analysis";
                enabled: root.file_loaded && !root.analysis_running;
                background: MaterialPalette.run;
                text_color: MaterialPalette.on_run;
                clicked => {
                    root.run_analysis();
                }
            }
        }

        // Progress Section (Visible only when running or has progressed)
        if root.analysis_running || root.analysis_done: VerticalLayout {
            spacing: MaterialStyleMetrics.spacing_2;
            MaterialText {
                text: root.analysis_status_text;
                color: MaterialPalette.on_surface_variant;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            LinearProgressIndicator {
                width: 100%;
                height: 8px;
                progress: root.progress;
                indeterminate: false;
            }
        }

        // Save Results
        write_area := TouchArea {
            FilledButton {
                width: 100%;
                text: "Save Results";
                enabled: root.analysis_done && !root.analysis_running;
                background: MaterialPalette.error;
                text_color: MaterialPalette.on_error;
                clicked => {
                    root.write_files();
                }
            }
        }
    }
}
