// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: MIT
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import {
    MaterialPalette,
    MaterialStyleMetrics,
    MaterialTypography,
    FilledButton,
    OutlinedCard,
    MaterialText,
    CheckBox,
    CheckState,
    TextField,
} from "@material";

export component RunAnalysisCard inherits OutlinedCard {
    in property <bool> file_loaded;
    in property <bool> analysis_running;
    in property <bool> analysis_done;
    in property <float> progress;
    in-out property <string> analysis_status_text;
    in-out property <bool> use_csv: true;
    in-out property <bool> use_hdf5: true;
    in-out property <string> min_frame;
    in-out property <string> max_frame;
    callback run_analysis();
    callback write_files();

    // Hover state for tooltip
    out property <bool> analysis_area_has_hover: analysis_area.has-hover;
    out property <bool> hdf5_area_has_hover: hdf5_area.has-hover;
    out property <bool> csv_area_has_hover: csv_area.has-hover;

    VerticalLayout {
        padding: MaterialStyleMetrics.spacing_8;
        spacing: MaterialStyleMetrics.spacing_4;
        MaterialText {
            text: "5. Run Analysis";
            style: MaterialTypography.title_small;
        }

        HorizontalLayout {
            spacing: MaterialStyleMetrics.spacing_8;
            csv_area := TouchArea {
                horizontal-stretch: 1;
                HorizontalLayout {
                    padding: MaterialStyleMetrics.padding_4;
                    Text {
                        vertical-alignment: center;
                        text: "Export as CSV";
                        width: 60%;
                    }

                    CheckBox {
                        enabled: root.file_loaded;
                        width: 20%;
                        check_state: root.use_csv ? CheckState.checked : CheckState.unchecked;
                        checked_state_changed(s) => {
                            root.use_csv = (s == CheckState.checked);
                        }
                    }
                }
            }

            hdf5_area := TouchArea {
                horizontal-stretch: 1;
                HorizontalLayout {
                    padding: MaterialStyleMetrics.padding_4;
                    Text {
                        vertical-alignment: center;
                        text: "Export as HDF5";
                        width: 60%;
                    }

                    CheckBox {
                        enabled: root.file_loaded;
                        width: 20%;
                        check_state: root.use_hdf5 ? CheckState.checked : CheckState.unchecked;
                        checked_state_changed(s) => {
                            root.use_hdf5 = (s == CheckState.checked);
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            spacing: MaterialStyleMetrics.spacing_8;
            TouchArea {
                horizontal-stretch: 1;
                TextField {
                    enabled: root.file_loaded;
                    width: 100%;
                    label: "Min Frame";
                    text <=> root.min_frame;
                }
            }

            TouchArea {
                horizontal-stretch: 1;
                TextField {
                    enabled: root.file_loaded;
                    width: 100%;
                    label: "Max Frame";
                    text <=> root.max_frame;
                }
            }
        }

        HorizontalLayout {
            spacing: MaterialStyleMetrics.spacing_8;
            analysis_area := TouchArea {
                min-height: 40px;
                horizontal-stretch: 1;
                FilledButton {
                    height: 100%;
                    width: 100%;
                    text: root.analysis_running ? "Analysis in Progress..." : "Run Analysis";
                    enabled: root.file_loaded && !root.analysis_running;
                    clicked => {
                        root.run_analysis();
                    }
                }
            }

            write_area := TouchArea {
                min-height: 40px;
                horizontal-stretch: 1;
                FilledButton {
                    height: 100%;
                    width: 100%;
                    text: "Write Files";
                    enabled: root.analysis_done && !root.analysis_running;
                    clicked => {
                        root.write_files();
                    }
                }
            }
        }

        if (root.analysis_running): Rectangle {
            height: 4px;
            width: 100%;
            background: MaterialPalette.surface;
            Rectangle {
                x: 0;
                y: 0;
                height: 100%;
                width: root.progress * parent.width;
                background: MaterialPalette.primary;
                animate width {
                    duration: 250ms;
                    easing: ease-out;
                }
            }
        }
    }
}
