// Correlation - Liquid and Amorphous Solid Analysis Tool
// Copyright © 2013-2026 Isaías Rodríguez (isurwars@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
// Full license: https://github.com/Isurwars/Correlation/blob/main/LICENSE

import { MaterialPalette } from "material/material.slint";

export component SplitterHandle inherits Rectangle {
    in-out property <bool> enabled: true;
    out property <bool> is_dragging: touch.pressed;
    callback moved(length);

    width: 6px;
    z: 10;

    Rectangle {
        width: touch.has-hover || root.is_dragging ? 3px : 1.5px;
        height: 100%;
        border-radius: 1px;
        background: root.is_dragging ? MaterialPalette.primary :
                    touch.has-hover ? MaterialPalette.primary.with_alpha(0.8) :
                    MaterialPalette.outline_variant.with_alpha(0.35);
        animate width { duration: 150ms; }
        animate background { duration: 150ms; }
    }

    touch := TouchArea {
        enabled: root.enabled;
        mouse-cursor: ew-resize;

        moved => {
            if (self.pressed) {
                root.moved(self.mouse-x - self.pressed-x);
            }
        }
    }
}
