import "fonts/FiraCode-Bold.ttf";

export global Theme {
    // brushes
    out property <brush> window-background: #0B0B0B;
    out property <brush> background-regular: #0B0B0B;
    out property <brush> background-hover: root.background-regular.brighter(0.2);
    out property <brush> background-pressed: root.background-regular.brighter(0.4);
    out property <brush> background-selected: root.foreground;
    out property <brush> background-selected-hover: root.background-selected.brighter(0.2);
    out property <brush> background-selected-pressed: root.background-selected.brighter(0.4);
    out property <brush> foreground: #FFFFFF;
    out property <brush> foreground-hover: root.foreground.darker(0.2);
    out property <brush> foreground-pressed: root.foreground.darker(0.4);
    out property <brush> foreground-selected: root.background-regular;
    out property <brush> foreground-selected-hover: root.foreground-selected.darker(0.2);
    out property <brush> foreground-selected-pressed: root.foreground-selected.darker(0.4);

    // Semantic Colors
    out property <brush> primary: #3B82F6;
    out property <brush> secondary: #64748B;
    out property <brush> accent: #0EA5E9;
    out property <brush> destructive: #EF4444;
    out property <brush> success: #22C55E;
    out property <brush> warning: #EAB308;
    out property <brush> white: #FFFFFF;
    out property <brush> black: #000000;
    out property <brush> transparent: Colors.transparent;

    // durations
    out property <duration> duration-fast: 100ms;
    out property <duration> duration-regular: 250ms;

    // radius
    out property <length> radius-small: 4px;
    out property <length> radius-regular: 8px;

    // sizes
    out property <length> size-small: 24px;
    out property <length> size-regular: 48px;
    out property <length> size-medium: 128px;
    out property <length> size-big: 170px;

    // spacings
    out property <length> spacing-regular: 4px;
    out property <length> spacing-medium: 8px;
    out property <length> spacing-large: 16px;

    // typo
    out property <string> font-family: "FiraCode";
    out property <length> font-size-regular: 12px;
    out property <length> font-size-medium: 14px;
    out property <length> font-size-large: 20px;
    out property <int> font-weight-regular: 400;
    out property <int> font-weight-bold: 900;
}
