import { Theme } from "Theme.slint";

export component ToolTip inherits Window {
    in property <string> text <=> text_element.text;
    in property <bool> user_is_hovering;

    always-on-top: true;
    z: 100;
    visible: user_is_hovering;
    Rectangle {
        visible: user_is_hovering;
        opacity: user_is_hovering ? 1.0 : 0.0;
        animate opacity {
            duration: 175ms;
            delay: 1000ms;
        }
        background: Theme.background-hover;
        border-radius: Theme.radius-small;
        border-width: 1px;
        border-color: Theme.background-selected-hover;

        text_element := Text {
            width: parent.width - Theme.spacing-medium;
            height: parent.height - Theme.spacing-medium;
            color: Theme.foreground-hover;
            font-size: root.default-font-size * 0.9;
            horizontal-alignment: left;
            vertical-alignment: top;
            wrap: word-wrap;
        }
    }
}
