import { Palette } from "std-widgets.slint";

export component ToolTip inherits Window {
    in property <string> text;
    in property <bool> user_is_hovering;
    in property <length> text_width;

    Rectangle {
        visible: user_is_hovering;
        opacity: user_is_hovering ? 1.0 : 0.0;
        animate opacity {
            duration: 175ms;
            delay: 1000ms;
        }
        background: Palette.accent-foreground;
        border-radius: 3px;
        height: 30px;
        width: text_width + 10px;

        Text {
            text: text;
            color: Palette.accent-background;
            width: text_width;
            font-size: root.default-font-size * 0.9;
            horizontal-alignment: center;
            vertical-alignment: top;
            wrap: word-wrap;
        }
    }
}

export component ToolTipArea inherits TouchArea {
    preferred-height: 100%;
    preferred-width: 100%;
    in property <string> text;
    in property <length> text_width;
    ToolTip {
        text: root.text;
        user_is_hovering: root.has-hover;
        text_width: root.text_width;
        x: root.mouse-x + 30px;
        y: root.mouse-y + 30px;
        z: 100;
    }
}
